name: Deploy Labor Deploy HTML to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy to Nginx
        run: |
          sudo cp -r $GITHUB_WORKSPACE/*.html /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          sudo systemctl restart nginx
